[options]
admin_passwd = $pbkdf2-sha512$600000$z5mz1jqnlBIiJERojfG.1w$AXxVyv6YNrCGMa4Q/CaoyArjR9qcbCCYLRu57.AWKw7tJWtNrNck8I6lx6HispX9OkgwHjAoLxse5P3FUnRlwA

db_host = localhost
db_port = 5433
db_user = odoo
db_password = odoo

db_name = graduation_project_db_new
dbfilter = ^graduation_project_db_new$

addons_path = C:/Odoo_Research/Odoo_Platform/odoo/addons,C:/Odoo_Research/Odoo_Platform/addons,C:/Odoo_Research/Odoo_Platform/custom_addons,C:/Odoo_Research/Odoo_Platform
http_interface = 127.0.0.1